name: 'XTRa-hook-shot'
description: 'Triggers a deploy server and handles the response'
inputs:
  data:
    description: 'JSON string data'
    required: true
    default: ''
  url:
    description: 'Endpoint URL'
    required: true
    default: ''
  headers:
    description: 'Optional headers'
    required: false
    default: ''
  eval_output:
    description: 'When false - job will not evaluate response code of the request'
    required: false
    default: 'true'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.data }}
    - ${{ inputs.url }}
    - ${{ inputs.headers }}
    - ${{ inputs.eval_output }}
branding:
  icon: 'cloud-lightning'
  color: 'blue'
  